package field.event.dialog.msg;

public enum MsgFrame {
	STD_FIXED = 0,
	STD_ADAPTIVE,
	SCREAM_FIXED,
	SCREAM_ADAPTIVE,
	CLOUD_ADAPTIVE,
	#ifdef SANGO
	PLACE_BLUE = 5,
	PLACE_GRAY,
	PLACE_BLACK,
	SYS_RED,
	PLACE_BEIGE,
	PLACE_BLUE2,
	#else if XY
	PLACE_MARBLE_BEIGEEDGE = 5,
	PLACE_MARBLE_REDEDGE,
	PLACE_HITECH_BLUE,
	PLACE_HITECH_GREEN,
	PLACE_BLUE,
	PLACE_GREEN,
	#endif
	SYS_BLACK = 11,
	BUBBLE_SMALL,
	SYS_BLACK_SMALL
}